"""Interactive setup wizard.

Creates or updates the .env file by prompting for the required values.
Never prints secrets to the terminal (password-style input is hidden).

Usage:
    python -m scripts.setup_wizard
"""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"


def _prompt(label: str, secret: bool = False) -> str:
    if secret:
        import getpass

        value = getpass.getpass(f"{label}: ")
    else:
        value = input(f"{label}: ")
    return value.strip()


def _prompt_int(label: str) -> int:
    while True:
        raw = _prompt(label)
        if raw.isdigit():
            return int(raw)
        print("  ⚠️ الرجاء إدخال رقم صحيح.")


def main() -> int:
    print("=" * 55)
    print("  إعداد بوت إدارة TikTok — Setup Wizard")
    print("=" * 55)
    print()

    existing: dict[str, str] = {}
    if ENV_PATH.exists():
        print(f"تم العثور على ملف إعدادات سابق: {ENV_PATH}")
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
        print("اترك الحقل فارغًا للاحتفاظ بالقيمة الحالية.\n")

    def ask(key: str, label: str, secret: bool = False) -> str:
        default = existing.get(key, "")
        if default and not secret:
            value = input(f"{label} [{default}]: ").strip()
            return value or default
        if default and secret:
            value = _prompt(f"{label} (اتركه فارغًا للاحتفاظ بالقيمة الحالية)", secret=True)
            return value or default
        return _prompt(label, secret=secret)

    # 1. Bot token
    token = ask("TELEGRAM_BOT_TOKEN", "Telegram Bot Token", secret=True)
    if not token:
        print("⚠️ رمز البوت مطلوب. أُلغيت العملية.")
        return 1

    # 2. Owner id
    owner_raw = ask("OWNER_TELEGRAM_ID", "Owner Telegram ID (رقم)")
    if owner_raw and owner_raw.isdigit():
        owner = int(owner_raw)
    else:
        owner = _prompt_int("Owner Telegram ID (أدخل رقمًا صحيحًا)")

    # 3. Database URL
    db_url = ask(
        "DATABASE_URL",
        "Database URL (PostgreSQL)",
    )

    # 4. Headless mode
    headless = ask("TIKTOK_BROWSER_HEADLESS", "Headless (true/false)").lower()
    if headless not in ("true", "false"):
        headless = "true"

    lines = [
        "# TikTok Cleaner Bot configuration (generated by setup wizard)",
        f"TELEGRAM_BOT_TOKEN={token}",
        f"OWNER_TELEGRAM_ID={owner}",
        f"DATABASE_URL={db_url}",
        f"TIKTOK_BROWSER_HEADLESS={headless}",
        "TIKTOK_AUTOMATION_ENABLED=true",
        "TIKTOK_PERSIST_SESSION=false",
        "LOG_LEVEL=INFO",
        "LOG_DIR=logs",
    ]

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print()
    print("✅ تم إنشاء ملف .env بنجاح.")
    print(f"   المسار: {ENV_PATH}")
    print()
    print("الخطوات التالية:")
    print("  1. pip install -r requirements.txt")
    print("  2. playwright install chromium")
    print("  3. alembic upgrade head   (أو سيقوم البوت بإنشاء الجداول تلقائيًا)")
    print("  4. python main.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
